src/Entity/Exception.php
<?php

namespace App\Entity;

use App\Repository\ExceptionRepository;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExceptionRepository::class)]
class Exception {

    private const REQUEST = "Symfony\Component\HttpFoundation\Request";
    private const FLATTEN_EXCEPTIONS = "Symfony\Component\ErrorHandler\Exception\FlattenException[]";

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Instance::class, cascade: ["persist"])]
    private ?Instance $instance = null;

    #[ORM\Column(type: Types::JSON)]
    private ?array $context = null;

    #[ORM\Column(type: Types::JSON)]
    private ?array $user = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $request = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $exceptions = null;


    private ?array $unserializedRequest = null;
    private ?array $unserializedExceptions = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTime $time = null;

    public function getId(): ?int {
        return $this->id;
    }

    public function getInstance(): ?Instance {
        return $this->instance;
    }

    public function setInstance(?Instance $instance): self {
        $this->instance = $instance;
        return $this;
    }

    public function getContext(): ?array {
        return $this->context;
    }

    public function setContext(?array $context): self {
        $this->context = $context;
        return $this;
    }

    public function getUser(): ?array {
        return $this->user;
    }

    public function setUser(?array $user): self {
        $this->user = $user;
        return $this;
    }

    public function getRequest(): ?array {
        if(!$this->unserializedRequest) {
            $this->unserializedRequest = json_decode($this->request, true);
        }

        return $this->unserializedRequest;
    }

    public function getTextRequest(): ?string {
        return $this->request;
    }

    public function setRequest(string $request): self {
        $this->request = $request;
        $this->unserializedRequest = null;

        return $this;
    }

    public function getExceptions(): ?array {
        if(!$this->unserializedExceptions) {
            $this->unserializedExceptions = json_decode($this->exceptions, true);
        }

        return $this->unserializedExceptions;
    }

    public function getFirstException(): ?array {
        if(!$this->unserializedExceptions) {
            $this->unserializedExceptions = json_decode($this->exceptions, true);
        }

        return $this->unserializedExceptions[0];
    }

    public function getTextExceptions(): ?string {
        return $this->exceptions;
    }

    public function setExceptions(string $exceptions): self {
        $this->exceptions = $exceptions;
        $this->unserializedExceptions = null;

        return $this;
    }

    public function getTime(): ?DateTime {
        return $this->time;
    }

    public function setTime(?DateTime $time): self {
        $this->time = $time;
        return $this;
    }

}

src/Controller/ExceptionController.php
<?php

namespace App\Controller;

use App\Entity\Exception;
use App\Entity\Instance;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/")]
class ExceptionController extends AbstractController {

    #[Route("/instance/{instance?}", name: "exception_list")]
    #[Route("/", name: "exception_list_index")]
    public function list(Request                $request,
                         PaginatorInterface     $paginator,
                         EntityManagerInterface $entityManager,
                         ?string                $instance): Response {
        $exceptionRepository = $entityManager->getRepository(Exception::class);
        $instanceRepository = $entityManager->getRepository(Instance::class);

        if ($instance) {
            $instance = $instanceRepository->findOneBy(["code" => $instance]);
            $exceptions = $exceptionRepository->queryInstance($instance);
        } else {
            $exceptions = $exceptionRepository->queryOrdered();
        }

        $exceptions = $paginator->paginate($exceptions, $request->get("page", 1), 15);

        foreach($exceptions as $exception) {
            $trace = $exception->getFirstException()["trace"];

            if(count($trace) >= 2) {
                $exception->method = $trace[1];
            } else {
                $exception->method = "/";
            }
        }

        return $this->render("exception/list.html.twig", [
            "current_instance" => $instance ?? null,
            "exceptions" => $exceptions,
        ]);
    }

    #[Route("/{instance}/show/{exception}", name: "exception_show")]
    public function show(Exception $exception): Response {
        return $this->render("exception/show.html.twig", [
            "current_instance" => $exception->getInstance(),
            "context" => $exception,
        ]);
    }

}

templates/exception/exception.html.twig
{% macro print_args(args) %}
    {%- for arg in args -%}
        {%- if arg[0] == 'object' -%}
            <span class="argument">{{ arg[1] }}{% if not loop.last %}, {% endif %}</span>
        {%- else -%}
            <span class="argument">{{ arg[1] }} ({{ arg[0] }}){% if not loop.last %}, {% endif %}</span>
        {%- endif -%}
    {%- endfor -%}
{% endmacro %}

{% import _self as macros %}

{% extends 'base.html.twig' %}

{% block content %}
    <div class="tab-control">
        <button data-target="#request">Request</button>
        <button data-target="#exception" class="active">Exceptions</button>
    </div>

    <div class="url">
        <b>{{ context.context.method }}</b>
        <a href="{{ context.context.uri }}" target="_blank">{{ context.context.uri }}</a>
    </div>
    <div class="exception">
        {{ context.exception.message }}

        <span class="code">HTTP {{ context.exception.statusCode }} - {{ context.exception.statusText }}</span>
    </div>

    <div id="request" class="tab hidden">
        <div class="colored">
            <h1>Headers</h1>
            {% for key, value in context.context.headers %}
                <b>{{ key | title }} :</b> {{ value[0] is defined ? value[0] : value }}<br>
            {% endfor %}
        </div>

        <div class="regular">
            <h1>Body</h1>
            not yet!
        </div>
    </div>

    <div id="exception" class="regular tab">
        <h1>{{ context.exception.class }}</h1>

        {% for trace in context.exception.trace %}
            <div class="trace">
                <div class="header">
                    <i class="toggle fas {% if loop.first %}fa-minus{% else %}fa-plus{% endif %}"></i>

                    {% if trace.short_class and trace.type and trace.function %}
                        <h1>{{ trace.short_class }}{{ trace.type }}{{ trace.function }}({{ macros.print_args(trace.args) }})</h1>
                    {% endif %}

                    <h2 title="{{ trace.file }}:{{ trace.line }}">in {{ trace.file }} (line {{ trace.line }})</h2>
                </div>

                <ol start="{{ trace.content | keys | first }}" {% if not loop.first %}class="d-none"{% endif %}>
                    {%- for number, line in trace.content -%}
                        <li {% if number == trace.line %}class="highlighted"{% endif %}><pre>{{- line -}}</pre></li>
                    {%- endfor -%}
                </ol>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/exception/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Exceptions list{% endblock %}

{% block content %}
    {% if current_instance %}
        <h1 class="title">Exceptions on instance <span class="bolder">{{ current_instance.code | upper }}</span></h1>
    {% else %}
        <h1 class="title">Exceptions on <span class="bolder">all instances</span></h1>
    {% endif %}

    <table>
        <thead>
        <tr>
            <th>ID</th>
            {% if not current_instance %}<th>Instance</th>{% endif %}
            <th>Request</th>
            <th>Method</th>
            <th>Exception</th>
            <th>Occurred</th>
        </tr>
        </thead>
        <tbody>
        {% for exception in exceptions %}
            <tr data-href="{{ path('exception_show', {'instance': exception.instance.code, 'exception': exception.id}) }}">
                <td><span class="muted">{{ exception.id }}</span></td>
                {% if not current_instance %}<td>{{ exception.instance.code }}</td>{% endif %}
                <td><small><strong>{{ exception.request.method }}</strong>
                        <u>{{ exception.request.requestUri | split('?')[0] | trim('/', 'right') }}</u></small></td>
                <td>{% include 'display_method.html.twig' with {trace: exception.method} %}</td>
                <td><strong>{{ exception.firstException.class | split('\\') | last }}</strong></td>
                <td>{{ exception.time | date('d/m/Y H:i:s') }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="navigation">
        {{ knp_pagination_render(exceptions) | replace({'&lt;&lt;': 'First', '&gt;&gt;': 'Last', '&lt;': 'Previous', '&gt;': 'Next'}) | raw }}
    </div>
{% endblock %}

templates/exception/show.html.twig
{% set encore_script = 'exception_show' %}
{% extends 'base.html.twig' %}

{% block title %}Log: {{ context.firstException.message }}{% endblock %}

{% block content %}
    <div class="tab-control">
        <button data-target="#request">Request</button>
        <button data-target=".exception" class="active">Exceptions</button>
    </div>

    <div class="url">
        <b>{{ context.request.method }}</b>
        <a href="{{ context.request.uri }}" target="_blank">{{ context.request.uri }}</a>
    </div>
    <div class="exception-message">
        {{ context.firstException.message }}
    </div>

    <div id="request" class="tab hidden">
        <div class="colored">
            <h1>Headers</h1>
            {% for key, value in context.request.headers %}
                <b>{{ key | title }}:</b> {{ value[0] is defined ? value[0] : value }}<br>
            {% endfor %}
        </div>

        <div class="row">
            <div class="regular">
                <h1>Query parameters</h1>
                {% for key, query in context.request.query %}
                    <b>{{ key }}:</b> {{ query }}<br>
                {% else %}
                    No query parameters were found
                {% endfor %}
            </div>

            <div class="regular">
                <h1>Request parameters</h1>
                {% for key, request in context.request.request %}
                    <b>{{ key }}:</b> {{ request }}<br>
                {% else %}
                    No request parameters were found
                {% endfor %}
            </div>
        </div>

        <div class="regular">
            <h1>Content</h1>
            {{ context.request.content ?: 'No body content' }}
        </div>
    </div>

    {% for exception in context.exceptions %}
        <div class="exception regular tab">
            <h1>{{ exception.class }}</h1>
            {% if not loop.first %}
                <span class="message">{{ exception.message }}</span>
            {% endif %}

            {% for trace in exception.trace %}
                {% set displayed = loop.first and loop.parent.loop.first %}

                <div class="trace">
                    <div class="header">
                        <i class="toggle fas {% if displayed %}fa-minus{% else %}fa-plus{% endif %}"></i>

                        {% include 'display_method.html.twig' with {trace: trace} %}

                        <h2 title="{{ trace.file }}:{{ trace.line }}">in {{ trace.file }} (line {{ trace.line }})</h2>
                    </div>

                    <ol start="{{ trace.content | keys | first }}" {% if not displayed %}class="hidden"{% endif %}>
                        {%- for number, line in trace.content -%}
                            <li {% if number == trace.line %}class="highlighted"{% endif %}>
                                <pre>{{- line -}}</pre>
                            </li>
                        {%- endfor -%}
                    </ol>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}